import { Plus_Jakarta_Sans } from "next/font/google"
import "./globals.css"
import Navbar from "./components/layout/Navbar"
const plusJakartaSans = Plus_Jakarta_Sans({
  weight: "400",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${plusJakartaSans.className}`}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
